{% set xorg_name = "libXaw" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.16" %}
{% set sha256 = "731d572b54c708f81e197a6afa8016918e2e06dfd3025e066ca642a5b8c39c8f" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0

requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - gnuconfig                    # [unix]
    - m2-base                      # [win]
    - make                         # [unix]
    - m2-make                      # [win]
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
  host:
    - pthread-stubs
    - xorg-libx11 >=1.6,<2
    # Additional constraintless xorg-libx11 dep below is for conda-build to add potential pinning to.
    - xorg-libx11
    - xorg-libxext 1.3.*
    - xorg-libxmu 1.2.*
    - xorg-libxpm >=3.5,<4
    - xorg-libxt >=1.1,<2
    - xorg-util-macros
    - xorg-xorgproto
  run:
    - {{ pin_compatible('xorg-libx11') }}

test:
  commands:
    # The library checks here are customized for unusual install results on Windows:
    {% set lib_idents = [ "Xaw6", "Xaw7" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    {% endfor %}
    - if not exist %PREFIX%/Library/bin/msys-Xaw-6.dll exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-Xaw-7.dll exit /b 1  # [win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 Athena widgets library.

extra:
  recipe-maintainers:
    - pkgw
