{% set xorg_name = "libXaw" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.14" %}
{% set sha256 = "76aef98ea3df92615faec28004b5ce4e5c6855e716fa16de40c32030722a6f8e" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ xorg_name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - make  # [unix]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - pthread-stubs
    - xorg-libx11 >=1.6,<2
    # Additional constraintless xorg-libx11 dep below is for conda-build to add potential pinning to.
    - xorg-libx11
    - xorg-libxext 1.3.*
    - xorg-libxmu 1.1.*
    - xorg-libxpm >=3.5,<4
    - xorg-libxt >=1.1,<2
    - xorg-util-macros
    - xorg-xextproto
    - xorg-xproto
  run:
    - {{ pin_compatible('xorg-libx11') }}
    - xorg-libxext 1.3.*
    - xorg-libxmu 1.1.*
    - {{ pin_compatible('xorg-libxpm') }}
    - {{ pin_compatible('xorg-libxt') }}

test:
  commands:
    # The library checks here are customized for unusual install results on Windows:
    {% set lib_idents = [ "Xaw6", "Xaw7" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    {% endfor %}
    - if not exist %PREFIX%/Library/bin/msys-Xaw-6.dll exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-Xaw-7.dll exit /b 1  # [win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 Athena widgets library.

extra:
  recipe-maintainers:
    - pkgw
