# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MIPOr5lZcDt4cNa3sSIYQ6V8hBqWS+N27eMC5uROJ0IMMMzcgzJJ6+UGgRrK8cM1LYmdQdjBqgd4DWNSuWeRLniTHic85oumM0UGdhupGP2I53UfA9XWtDw+w8dAfBRI7dbQgboV+u8Maqi2kFQ35a+G2QFekQbZ5Cs28ITQZdQdMltj0eKyV9W5E/wnSrWP0V2L3BDSIEiRIVFaWN3l1fTO0FxQplHCY5peQs6E4C//rFi/guow6/OH8YU2hTaN1strW+LJKIQUd4l/w/AlSexImvjD+3PW2C3QHAifQAQvFz+o4LKtpupjBtkZK30ZzS++owUWpUPG7ghpQ7J9dXdV2xp9+2RAM4DV/ZPvDpdE/W83B3v/NuOECSYluhVwEFxzgAd/o0rLgL+d3RMFZrLABRMFeWfObVzjFvabEtilISsemQ8DKZULQ2y29jlKhR9hX5jEU+N4vrBuja7YXLapNl47TZhGIyXPelLo+yJU6oInLPeAOlj/IEYL3r8/MOLTOaDio6PLJx/cRe/3GYGbAhiIEGI9anZYZE7403ZioKAi3BypEH8Bu7VQlVrUnNrvqihsJXCX80jw2SloI3bOjzfs5jACNLQ7MX0BV3hSlwC+OPUrP/GQu1Qw2gfV/KQEZuJffQpIOnRBlk2p6R1bg/nWU7/y+r/kDPaE+10="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
