travis:
  secure:
    BINSTAR_TOKEN: MIPOr5lZcDt4cNa3sSIYQ6V8hBqWS+N27eMC5uROJ0IMMMzcgzJJ6+UGgRrK8cM1LYmdQdjBqgd4DWNSuWeRLniTHic85oumM0UGdhupGP2I53UfA9XWtDw+w8dAfBRI7dbQgboV+u8Maqi2kFQ35a+G2QFekQbZ5Cs28ITQZdQdMltj0eKyV9W5E/wnSrWP0V2L3BDSIEiRIVFaWN3l1fTO0FxQplHCY5peQs6E4C//rFi/guow6/OH8YU2hTaN1strW+LJKIQUd4l/w/AlSexImvjD+3PW2C3QHAifQAQvFz+o4LKtpupjBtkZK30ZzS++owUWpUPG7ghpQ7J9dXdV2xp9+2RAM4DV/ZPvDpdE/W83B3v/NuOECSYluhVwEFxzgAd/o0rLgL+d3RMFZrLABRMFeWfObVzjFvabEtilISsemQ8DKZULQ2y29jlKhR9hX5jEU+N4vrBuja7YXLapNl47TZhGIyXPelLo+yJU6oInLPeAOlj/IEYL3r8/MOLTOaDio6PLJx/cRe/3GYGbAhiIEGI9anZYZE7403ZioKAi3BypEH8Bu7VQlVrUnNrvqihsJXCX80jw2SloI3bOjzfs5jACNLQ7MX0BV3hSlwC+OPUrP/GQu1Qw2gfV/KQEZuJffQpIOnRBlk2p6R1bg/nWU7/y+r/kDPaE+10=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
