appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mtSar+ddbeBgohbl95VA16ZYqWSnsuPYDbJp8irkf0ym3SLj51wAumSijphK0ItQC5TW810JOhHeT4N0UPxs1Xfy2mxsI+GV5SBZBVo2njYrqKwReAropeVqLNaIkYwR8XdMJIhh9/y0G9rdV/x9Oqa1I6kFq2jaR69ZzvbsrTku8TTUj1Rh3WkEX5DJ0zQMdRsJDzWJnjckysuh139I24HuDZUFZ5F8FmXHrpF3Urpa+69tbKq9Ly0HA1OwEdPIGphssXaNsQM6zlqZonr1YB44qRZmvx5aU++fLgg4oV7ooUHugLQs7Wo4NiAaKjykuVG5bOylzI+FDXLmhIgaveK/1CXfJEn1qM5PPZ0q5WBNDh7YfyHMQ+YrlSmx4MRz1O5V4MM+64IxaJK6frZO3uZ4OSGOjXcNExQDXByDob19g2k73W+6oMq19Uhyqsp7R0rYFmd5SgzP4wmQ/XBMRRsS7uGP8kNkP+IirEUasVrXFJ3AaeY0uKwuhuvh8CA9w6WRoVpQcRhi01BS+A0CyKMf8rGxrZQ0XkM6v1XNJ08re8XK1lHgF58b3xB9PJuwvD68T5DONUBhFWr3eLLQXHQLWtL74ACEyJGNr0KNIRVCoYAMQPDtOQaxndb8y6iB5rQpngWbAYFXKpzsfOoMC/NxLQ2KHZV3y0ETynm0xkk=}
